### ISSUE TITLE
Project State and Usage Permission

### ISSUE THREAD

**Issue by DSoko2** [inrick/Featherweight-Java#1]
Dear @inrick,

on my search for a Featherweight Java implementation I stumbled over this great project of yours. I would love to learn more about the project and its context and would be very happy if you would answer me some related questions:

* In which context did you develop this project? Was it used or applied in another project?
* Would you think extending this project with generics à la GJ to achieve Featherweight GJ as proposed in the original Featherweight java papers would be reasonable or even a straight forward extension?
* Unfortunately, this repo does not contain a license: Would you agree with others using, altering and extending this code in the context of research projects?

I am looking forward to a reply of yours and thank you a lot for the work on this! If you would prefer, you can also reach me via mail: sokolowski@cs.tu-darmstadt.de

Best regards,
Daniel

**Comment by inrick** [comment]
Hi Daniel,

Thank you for the kind words. However, this is an old project bound to disappoint. It's only an implementation of Featherweight Java's typing rules, and a rather bad one at that. I was quite new to programming, especially of the functional variety. For example, the program just keeps a list of all the classes and dynamically computes relations instead of simply building a tree. On the other hand it's thin on abstractions and should be easy to understand, though it's very unidiomatic Haskell.

To answer each question:

1. It was a part of my bachelor's thesis project back in 2010 and was never applied elsewhere. The code uploaded to Github is slightly modified. (https://www.csc.kth.se/utbildning/kandidatexjobb/datateknik/2010/rapport/carlstrom_fabian_K10064.pdf)

2. I suspect you would not gain much from basing an implementation of FGJs typing rules on this. It is not a solid foundation and FGJ would likely require rewriting most of it anyway. And you probably want the understanding that comes with building the simpler thing first.

3. Feel free to use the code in any way you like, I'd only warn of its quality. If you find it useful I'm only glad! I consider the code to be in the public domain.

Kind regards,
Fabian

**Comment by DSoko2** [comment]
Dear Fabian,

thanks a lot for the honest and very helpful reply, it is much appreciated!

Best regards,
Daniel
